trigger:
- master

variables:
  windowsCompiler: win64_msvc2017_64
  windowsFile: qt-unified-windows-x86-online.exe
  macCompiler: clang_64
  macFile: qt-unified-mac-x64-online.dmg
  linuxCompiler: gcc_64
  linuxFile: qt-unified-linux-x64-online.run
  Qt: 5.12.6
  script: unattended_env.qs

jobs:
# WINDOWS JOB DEFINITION
- job:
  displayName: Windows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(windowsFile)
      chmod +x $(windowsFile)
      set QT_VERSION=$(Qt)
      set QT_COMPONENTS=$(windowsCompiler),qtscript,qtwebengine
      set QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      $(windowsFile) --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
      cd $(Agent.BuildDirectory)/Qt/$(Qt)/msvc2017_64/lib/cmake/Qt5
      ls -l
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

# MACOS JOB DEFINITION
- job:
  displayName: macOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(macFile)
      sudo chmod +x ./$(macFile)
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(macCompiler),qtscript, qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      hdiutil attach $(macFile)
      open -a /Volumes/qt-unified-mac-x64-3.1.1-online/qt-unified-mac-x64-3.1.1-online.app --args --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
      cd $(Agent.BuildDirectory)/Qt/$(Qt)/$(macCompiler)/lib/cmake/Qt5
      ls -l
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

    # LINUX JOB DEFINITION
- job:
  displayName: Ubuntu
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(linuxFile)
      sudo chmod +x ./$(linuxFile)
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(linuxCompiler),qtscript, qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      ./$(linuxFile) --platform minimal --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
      cd $(Agent.BuildDirectory)/Qt/$(Qt)/$(linuxCompiler)/lib/cmake/Qt5
      ls -l
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'
