trigger:
- master

variables:
  windowsCompiler: win64_msvc2017_64
  windowsFile: qt-unified-windows-x86-online.exe
  macCompiler: clang_64
  macFile: qt-unified-mac-x64-online.dmg
  linuxCompiler: gcc_64
  linuxFile: qt-unified-linux-x64-online.run
  Qt: 5.12.6
  script: unattended_env.qs

jobs:
# WINDOWS JOB DEFINITION
- job:
  displayName: Windows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016 '

  steps:
  - script: |
      mkdir Qt
      curl -O http://download.qt.io/official_releases/online_installers/$(windowsFile)
      set QT_VERSION=$(Qt)
      set QT_COMPONENTS=$(windowsCompiler),qtscript, qtwebengine
      set QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      $(windowsFile) --platform minimal --no-force-installations --verbose --script $(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

# MACOS JOB DEFINITION
- job:
  displayName: macOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      mkdir Qt
      curl -O http://download.qt.io/official_releases/online_installers/$(macFile)
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(macCompiler),qtscript, qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      ./$(macFile) --platform minimal --no-force-installations --verbose --script $(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

    # LINUX JOB DEFINITION
- job:
  displayName: Ubuntu
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(linuxFile)
      sudo chmod +x ./qt-unified-linux-x64-online.run
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(linuxCompiler),qtscript, qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      ls -l
      dir
      ./$(linuxFile) --platform minimal --no-force-installations --verbose --script $(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'
