trigger:
- master

variables:
  JFlag: '-j 8'
  Makefiles: Unix Makefiles
  VisualStudio: Visual Studio 15 2017 Win64
  windowsCompiler: win64_msvc2017_64
  windowsFile: qt-unified-windows-x86-online.exe
  macCompiler: clang_64
  macFile: qt-unified-mac-x64-online.dmg
  linuxCompiler: gcc_64
  linuxFile: qt-unified-linux-x64-online.run
  Qt: 5.12.6
  script: unattended_env.qs

jobs:
# WINDOWS JOB DEFINITION
- job:
  displayName: Windows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016 '
  strategy:
    matrix:
      64-bit Debug:
        BuildType: Debug
      64-bit Release:
        BuildType: Release

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(windowsFile)
      chmod +x $(windowsFile)
      set QT_VERSION=$(Qt)
      set QT_COMPONENTS=$(windowsCompiler),qtscript,qtwebengine
      set QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      $(windowsFile) --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

  - task: CMake@1
    displayName: 'Configure MITK for $(BuildType)'
    inputs:
      cmakeArgs: '.. -G"$(VisualStudio)" -DQt5_DIR:PATH=$(Agent.BuildDirectory)/Qt/$(Qt)/msvc2017_64/lib/cmake/Qt5/ -DBUILD_TESTING:BOOL=OFF'

  - task: CMake@1
    displayName: 'Build MITK for $(BuildType)'
    inputs:
      cmakeArgs: '--build . --config $(BuildType)'

# MACOS JOB DEFINITION
- job:
  displayName: macOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(macFile)
      sudo chmod +x ./$(macFile)
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(macCompiler),qtscript,qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      hdiutil attach $(macFile)
      cd /Volumes/qt-unified-mac-x64-3.1.1-online/qt-unified-mac-x64-3.1.1-online.app/Contents/MacOS
      ./qt-unified-mac-x64-3.1.1-online --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

  - task: CMake@1
    displayName: 'Configure MITK for $(BuildType)'
    inputs:
      cmakeArgs: '..  -G"$(Makefiles)" -DQt5_DIR:PATH=$(Agent.BuildDirectory)/Qt/$(Qt)/$(macCompiler)/lib/cmake/Qt5/ -DBUILD_TESTING:BOOL=OFF'

  - task: CMake@1
    displayName: 'Build MITK for $(BuildType)'
    inputs:
      cmakeArgs: '--build . --config $(BuildType) $(JFlag)'

# LINUX JOB DEFINITION
- job:
  displayName: Ubuntu
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - script: |
      version=3.14
      build=5
      mkdir ../temp
      cd ../temp
      wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
      tar -xzvf cmake-$version.$build.tar.gz
      cd cmake-$version.$build/
      ./bootstrap
      make -j$(nproc)
      sudo make install
    displayName: 'Download and update CMake'

  - script: |
      sudo apt update
      sudo apt install libglu1-mesa-dev mesa-common-dev
    displayName: 'Install prerequisites'

  - script: |
      mkdir Qt
      curl -O -J -L http://download.qt.io/official_releases/online_installers/$(linuxFile)
      sudo chmod +x ./$(linuxFile)
      export QT_VERSION=$(Qt)
      export QT_COMPONENTS=$(linuxCompiler),qtscript,qtwebengine
      export QT_TARGET_DIR=$(Agent.BuildDirectory)/Qt
      ./$(linuxFile) --platform minimal --no-force-installations --verbose --script $(Agent.BuildDirectory)/s/$(script)
    workingDirectory: '$(Agent.BuildDirectory)'
    displayName: 'Download and install Qt'

  - task: CMake@1
    displayName: 'Configure MITK for $(BuildType)'
    inputs:
      cmakeArgs: '..  -G"$(Makefiles)" -DQt5_DIR:PATH=$(Agent.BuildDirectory)/Qt/$(Qt)/$(linuxCompiler)/lib/cmake/Qt5/ -DBUILD_TESTING:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON'

  - task: CMake@1
    displayName: 'Build MITK for $(BuildType)'
    inputs:
      cmakeArgs: '--build . --config $(BuildType)'
